# Generated by Django 4.0.4 on 2022-05-08 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(default='default.jpg', upload_to='photo')),
                ('bank', models.TextField()),
                ('acc_no', models.IntegerField(null=True)),
                ('ifsc', models.TextField()),
                ('ctc', models.IntegerField(null=True)),
                ('aadhaar_card', models.FileField(upload_to='aadhaar_card')),
                ('pan_card', models.FileField(upload_to='pan_card')),
                ('cibil_score', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('tenure', models.FloatField()),
                ('interest_rate', models.IntegerField()),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('date_borrowing_start', models.DateField()),
                ('date_lending_end', models.DateField()),
                ('borrowing_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_borrowing', to=settings.AUTH_USER_MODEL)),
                ('interested_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('lending_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
