# Generated by Django 4.0.4 on 2022-05-08 14:06

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aadhaar_card',
            field=models.FileField(upload_to='aadhaar_card', verbose_name='Aadhaar card'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='acc_no',
            field=models.CharField(max_length=40, null=True, validators=[core.models.bank_acc_no], verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank',
            field=models.CharField(max_length=100, verbose_name='Bank name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cibil_score',
            field=models.IntegerField(null=True, verbose_name='Cibil score'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ctc',
            field=models.IntegerField(null=True, verbose_name='CTC'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ifsc',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Bank IFSC'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(max_length=50, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pan_card',
            field=models.FileField(upload_to='pan_card', verbose_name='Pan card'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='photo', verbose_name='Photo'),
        ),
    ]
