# Generated by Django 4.0.4 on 2022-05-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_first_name_alter_profile_ifsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
    ]
