# Generated by Django 4.0.4 on 2022-05-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_ctc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name'),
        ),
    ]
