# Generated by Django 4.0.4 on 2022-05-08 19:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='acc_no',
            field=models.CharField(max_length=40, null=True, validators=[core.models.bank_acc_no], verbose_name='Account Number'),
        ),
    ]
