# Generated by Django 4.0.4 on 2022-05-08 19:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_profile_acc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ifsc',
            field=models.CharField(max_length=11, validators=[core.models.ifsc], verbose_name='IFSC Code'),
        ),
    ]
