# Generated by Django 4.0.4 on 2022-05-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_profile_ifsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='photo', verbose_name='Profile picture'),
        ),
    ]
