# Generated by Django 4.0.4 on 2022-05-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aadhaar_card',
            field=models.FileField(blank=True, upload_to='aadhaar_card', verbose_name='Aadhaar card'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pan_card',
            field=models.FileField(blank=True, upload_to='pan_card', verbose_name='Pan card'),
        ),
    ]
