# Generated by Django 4.0.4 on 2022-05-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_loan_date_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='tenure',
            field=models.IntegerField(),
        ),
    ]
