# Generated by Django 4.0.4 on 2022-05-09 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_loan_interested_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='tenure',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Tenure (in months)'),
        ),
    ]
