# Generated by Django 4.0.4 on 2022-05-09 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_alter_loan_tenure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interested_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
