# Generated by Django 4.0.4 on 2022-05-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_loan_interested_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='interested_users',
        ),
    ]
