# Generated by Django 4.0.4 on 2022-05-09 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_remove_loan_interested_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifiedLoan',
            fields=[
                ('loan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('offering_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
