# Generated by Django 4.0.4 on 2022-05-09 15:37

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_modifiedloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedloan',
            name='new_interest_rate',
            field=models.FloatField(default=0, validators=[core.models.interest_rate], verbose_name='New Interest rate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modifiedloan',
            name='new_tenure',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='New Tenure (in months)'),
            preserve_default=False,
        ),
    ]
