# Generated by Django 4.0.4 on 2022-05-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_modifiedloan_new_interest_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modifiedloan',
            old_name='new_interest_rate',
            new_name='interest_rate',
        ),
        migrations.RenameField(
            model_name='modifiedloan',
            old_name='new_tenure',
            new_name='tenure',
        ),
    ]
