# Generated by Django 4.0.4 on 2022-05-09 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_alter_loan_tenure_alter_modifiedloan_tenure'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedloan',
            name='borrowing_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_borrowing', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modifiedloan',
            name='offering_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lending', to=settings.AUTH_USER_MODEL),
        ),
    ]
