# Generated by Django 4.0.4 on 2022-05-09 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_modifiedloan_borrowing_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modifiedloan',
            old_name='loan_id',
            new_name='offer_id',
        ),
        migrations.AddField(
            model_name='modifiedloan',
            name='loan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.loan'),
            preserve_default=False,
        ),
    ]
