# Generated by Django 4.0.4 on 2022-05-09 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_remove_modifiedloan_borrowing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedloan',
            name='borrowing_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_borrowing', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modifiedloan',
            name='offering_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_offering', to=settings.AUTH_USER_MODEL),
        ),
    ]
