# Generated by Django 4.0.4 on 2022-05-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_modifiedloan_borrowing_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aadhaar_card',
            field=models.ImageField(blank=True, upload_to='aadhaar_card', verbose_name='Aadhaar card'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pan_card',
            field=models.ImageField(blank=True, upload_to='pan_card', verbose_name='Pan card'),
        ),
    ]
