# Generated by Django 4.0.4 on 2022-05-10 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0032_salaryslip_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedLoan',
            fields=[
                ('rejected_loan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loan')),
                ('rejected_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
