# Generated by Django 4.0.4 on 2022-05-10 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0033_rejectedloan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejectedloan',
            name='rejected_user',
        ),
        migrations.AddField(
            model_name='rejectedloan',
            name='borrowing_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_borrowing', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rejectedloan',
            name='rejecting_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rejecting', to=settings.AUTH_USER_MODEL),
        ),
    ]
