# Generated by Django 4.0.4 on 2022-05-10 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_remove_rejectedloan_rejected_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejectedloan',
            name='borrowing_user',
        ),
        migrations.AlterField(
            model_name='rejectedloan',
            name='rejecting_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
